In [9]:
outlook=['sunny','sunny','overcast','rainy','rainy','rainy',
         'overcast','sunny','sunny','rainy','sunny',
         'overcast','overcast','rainy']  
temperature=['hot','hot','hot','mild','cool','cool','cool','mild',
             'cool','mild','mild','mild','hot','mild']
humidity=['high','high','high','high','normal','normal',
          'normal','high','normal','normal','normal','high','normal','high']

wind=['weak','strong','weak','weak','weak','strong','strong','weak',
      'weak','weak','strong','strong','weak','strong']

play=['no','no','yes','yes','yes','no','yes','no','yes','yes',
      'yes','yes','yes','no']

## Encoding

### 3 Types of Encoding:

1. **Label Encoding**  
   Label encoding is used to convert categorical values into numerical values by assigning a unique integer to each category.

2. **OneHot Encoding**  
   OneHot encoding converts categorical data into binary vectors, where each category is represented by a column with a 1 or 0 indicating the presence of that category.

3. **get_dummies**  
   `get_dummies` is a function in pandas used to convert categorical variables into dummy/indicator variables, similar to OneHot Encoding but using pandas' functionality.


In [10]:
#Label Encoding : Converts categorical values into numerical labels (e.g., ["Red", "Blue", "Green"] → [0, 1, 2])
#In most cases , labels with high count gets heigher number
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
outlook_encoder=label.fit_transform(outlook)
outlook_encoder

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [11]:
temperature_encoder=label.fit_transform(temperature)
temperature_encoder

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [12]:
humidity_encoder=label.fit_transform(humidity)
humidity_encoder

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0])

In [13]:
wind_encoder=label.fit_transform(wind)
wind_encoder

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0])

In [14]:
features=list(zip(outlook_encoder,temperature_encoder,humidity_encoder,wind_encoder))
features

[(np.int64(2), np.int64(1), np.int64(0), np.int64(1)),
 (np.int64(2), np.int64(1), np.int64(0), np.int64(0)),
 (np.int64(0), np.int64(1), np.int64(0), np.int64(1)),
 (np.int64(1), np.int64(2), np.int64(0), np.int64(1)),
 (np.int64(1), np.int64(0), np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(0), np.int64(1), np.int64(0)),
 (np.int64(0), np.int64(0), np.int64(1), np.int64(0)),
 (np.int64(2), np.int64(2), np.int64(0), np.int64(1)),
 (np.int64(2), np.int64(0), np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(2), np.int64(1), np.int64(1)),
 (np.int64(2), np.int64(2), np.int64(1), np.int64(0)),
 (np.int64(0), np.int64(2), np.int64(0), np.int64(0)),
 (np.int64(0), np.int64(1), np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(2), np.int64(0), np.int64(0))]

## Model Creation

### 3 Types of Classifiers:

1. **Gaussian Naive Bayes**  
   Used for continuous/numerical data, assuming that the data follows a Gaussian (normal) distribution.

2. **Multinomial Naive Bayes**  
   Used for discrete (categorical or object) data, especially for classification problems where features are counts or frequencies (e.g., text classification).

3. **Bernoulli Naive Bayes**  
   Used for binary/boolean data, where features are binary (e.g., 0 or 1, True or False).


In [15]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(features,play)
print(model.predict([[2,0,0,0]]))

['no']
